Name:           ros-hydro-pr2-bringup-tests
Version:        1.0.2
Release:        0%{?dist}
Summary:        ROS pr2_bringup_tests package

Group:          Development/Libraries
License:        BSD
URL:            http://ros.org/wiki/pr2_bringup_tests
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-hydro-camera-calibration
Requires:       ros-hydro-ethercat-trigger-controllers
Requires:       ros-hydro-image-view
Requires:       ros-hydro-pr2-bringup
Requires:       ros-hydro-pr2-controller-manager
Requires:       ros-hydro-pr2-mannequin-mode
BuildRequires:  ros-hydro-camera-calibration
BuildRequires:  ros-hydro-catkin
BuildRequires:  ros-hydro-ethercat-trigger-controllers
BuildRequires:  ros-hydro-image-view
BuildRequires:  ros-hydro-pr2-bringup
BuildRequires:  ros-hydro-pr2-controller-manager
BuildRequires:  ros-hydro-pr2-mannequin-mode

%description
Complete functionality tests for PR2. Contains utilities designed to test and
verify devices, mechanicals and sensors.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/hydro/setup.sh" ]; then . "/opt/ros/hydro/setup.sh"; fi
mkdir -p build && cd build
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/hydro" \
        -DCMAKE_PREFIX_PATH="/opt/ros/hydro" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/hydro/setup.sh" ]; then . "/opt/ros/hydro/setup.sh"; fi
cd build
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/hydro

%changelog
* Tue Sep 16 2014 Devon Ash <dash@clearpathrobotics.com> - 1.0.2-0
- Autogenerated by Bloom

