%bcond_without weak_deps

%global __os_install_post %(echo '%{__os_install_post}' | sed -e 's!/usr/lib[^[:space:]]*/brp-python-bytecompile[[:space:]].*$!!g')
%global __provides_exclude_from ^/opt/ros/noetic/.*$
%global __requires_exclude_from ^/opt/ros/noetic/.*$

Name:           ros-noetic-pr2-motor-diagnostic-tool
Version:        1.0.15
Release:        1%{?dist}%{?release_suffix}
Summary:        ROS pr2_motor_diagnostic_tool package

License:        BSD
URL:            http://ros.org/wiki/pr2_motor_diagnostic_tool
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-noetic-ethercat-hardware
Requires:       ros-noetic-pluginlib
Requires:       ros-noetic-pr2-controller-interface
Requires:       ros-noetic-pr2-mechanism-model
Requires:       ros-noetic-pr2-mechanism-msgs
Requires:       ros-noetic-rospy
Requires:       ros-noetic-rqt-gui
Requires:       ros-noetic-rqt-gui-py
BuildRequires:  ros-noetic-catkin
BuildRequires:  ros-noetic-ethercat-hardware
BuildRequires:  ros-noetic-pluginlib
BuildRequires:  ros-noetic-pr2-controller-interface
BuildRequires:  ros-noetic-pr2-mechanism-model
BuildRequires:  ros-noetic-pr2-mechanism-msgs
BuildRequires:  ros-noetic-rospy
BuildRequires:  ros-noetic-rqt-gui
BuildRequires:  ros-noetic-rqt-gui-py
Provides:       %{name}-devel = %{version}-%{release}
Provides:       %{name}-doc = %{version}-%{release}
Provides:       %{name}-runtime = %{version}-%{release}

%description
pr2_motor_diagnostic_tool

%prep
%autosetup -p1

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/noetic/setup.sh" ]; then . "/opt/ros/noetic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake3 \
    -UINCLUDE_INSTALL_DIR \
    -ULIB_INSTALL_DIR \
    -USYSCONF_INSTALL_DIR \
    -USHARE_INSTALL_PREFIX \
    -ULIB_SUFFIX \
    -DCMAKE_INSTALL_PREFIX="/opt/ros/noetic" \
    -DCMAKE_PREFIX_PATH="/opt/ros/noetic" \
    -DSETUPTOOLS_DEB_LAYOUT=OFF \
    -DCATKIN_BUILD_BINARY_PACKAGE="1" \
    ..

%make_build

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/noetic/setup.sh" ]; then . "/opt/ros/noetic/setup.sh"; fi
%make_install -C obj-%{_target_platform}

%files
/opt/ros/noetic

%changelog
* Sat Jun 12 2021 David Feil-Seifer <dave@cse.unr.edu> - 1.0.15-1
- Autogenerated by Bloom

