Name:           ros-hydro-joint-qualification-controllers
Version:        1.0.2
Release:        0%{?dist}
Summary:        ROS joint_qualification_controllers package

Group:          Development/Libraries
License:        BSD
URL:            http://www.ros.org/wiki/joint_qualification_controllers
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-hydro-control-toolbox
Requires:       ros-hydro-pluginlib
Requires:       ros-hydro-pr2-controller-interface
Requires:       ros-hydro-pr2-hardware-interface
Requires:       ros-hydro-pr2-mechanism-model
Requires:       ros-hydro-realtime-tools
Requires:       ros-hydro-robot-mechanism-controllers
Requires:       ros-hydro-roscpp
Requires:       ros-hydro-sensor-msgs
Requires:       ros-hydro-std-msgs
Requires:       ros-hydro-urdf
BuildRequires:  ros-hydro-catkin
BuildRequires:  ros-hydro-control-toolbox
BuildRequires:  ros-hydro-pluginlib
BuildRequires:  ros-hydro-pr2-controller-interface
BuildRequires:  ros-hydro-pr2-hardware-interface
BuildRequires:  ros-hydro-pr2-mechanism-model
BuildRequires:  ros-hydro-realtime-tools
BuildRequires:  ros-hydro-robot-mechanism-controllers
BuildRequires:  ros-hydro-roscpp
BuildRequires:  ros-hydro-sensor-msgs
BuildRequires:  ros-hydro-std-msgs
BuildRequires:  ros-hydro-urdf

%description
Controllers used in PR2 hardware testing. For testing counterbalance of PR2, and
for internal WG use.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/hydro/setup.sh" ]; then . "/opt/ros/hydro/setup.sh"; fi
mkdir -p build && cd build
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/hydro" \
        -DCMAKE_PREFIX_PATH="/opt/ros/hydro" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/hydro/setup.sh" ]; then . "/opt/ros/hydro/setup.sh"; fi
cd build
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/hydro

%changelog
* Tue Sep 16 2014 Devon Ash <dash@clearpathrobotics.com> - 1.0.2-0
- Autogenerated by Bloom

