Name:           ros-indigo-pr2-motor-diagnostic-tool
Version:        1.0.15
Release:        1%{?dist}
Summary:        ROS pr2_motor_diagnostic_tool package

Group:          Development/Libraries
License:        BSD
URL:            http://ros.org/wiki/pr2_motor_diagnostic_tool
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-indigo-ethercat-hardware
Requires:       ros-indigo-pluginlib
Requires:       ros-indigo-pr2-controller-interface
Requires:       ros-indigo-pr2-mechanism-model
Requires:       ros-indigo-pr2-mechanism-msgs
Requires:       ros-indigo-rospy
Requires:       ros-indigo-rqt-gui
Requires:       ros-indigo-rqt-gui-py
BuildRequires:  ros-indigo-catkin
BuildRequires:  ros-indigo-ethercat-hardware
BuildRequires:  ros-indigo-pluginlib
BuildRequires:  ros-indigo-pr2-controller-interface
BuildRequires:  ros-indigo-pr2-mechanism-model
BuildRequires:  ros-indigo-pr2-mechanism-msgs
BuildRequires:  ros-indigo-rospy
BuildRequires:  ros-indigo-rqt-gui
BuildRequires:  ros-indigo-rqt-gui-py

%description
pr2_motor_diagnostic_tool

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/indigo" \
        -DCMAKE_PREFIX_PATH="/opt/ros/indigo" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/indigo

%changelog
* Wed Apr 24 2019 David Feil-Seifer <dave@cse.unr.edu> - 1.0.15-1
- Autogenerated by Bloom

